repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -v
        language: system
        pass_filenames: false

      - id: ruff-check
        name: ruff check
        entry: ruff check .
        language: system
        pass_filenames: false

      - id: black-check
        name: black-check
        entry: black --check . 
        language: system
        pass_filenames: false

      - id: black-format
        name: black format
        entry: black .
        language: system
        pass_filenames: false